### ISSUE TITLE
Poisson cost function does not run with other cost functions

### ISSUE THREAD

**Issue by Shanrahan16** [fitbenchmarking/fitbenchmarking#1071] opened 2022-10-17 14:44 UTC
**Description of the error**
Poisson cost function does not run with other cost functions, on the `NIST/low_difficulty` or `SASView_Simple_Shapes_1D` problem sets.

**Describe the expected result**
The Poisson cost function to run with all combinations of other cost functions.

**Describe the actual result**
The following combinations work:
```
nlls, weighted_nlls
poisson
nlls, weighted_nlls, hellinger_nlls
```
The following combinations do not work:
```
nlls, weighted_nlls, hellinger_nlls, poisson
nlls, weighted_nlls, poisson
nlls, poisson
weighted_nlls, poisson
```
The following message is produced:
```
[14:36:59]  INFO main.py: Producing output for the NIST_low_difficulty problem set
[14:36:59]  ERROR exception_handler.py: Unknown exception. Exiting.
```

**Suggested fix**

**Additional details**

**Comment by tyronerees** [comment] 2023-01-11 11:59
I've just run this, and it seems that this error may or may not arise, depending on the problem set run.  For example, when I run `fitbenchmarking -p examples/benchmark_problems/NIST/low_difficulty/ -c weighted_nlls poisson -s scipy -d`, the tables are produced as expected:

![image](https://user-images.githubusercontent.com/13645545/211800488-578df00a-bee9-48ad-ac2d-fe986b5134e8.png)

**Comment by tyronerees** [comment] 2023-01-13 09:39
I've been able to reproduce this issue when running with both `scipy` and `scipy_ls`.  The problem is `scipy_ls` can't handle the poisson cost function, which is handled gracefully when the tests are being run, but not when the results are being displayed.  Here is the full debug output:

![image](https://user-images.githubusercontent.com/13645545/212287892-85c83781-0122-49ec-97a3-85125b65ef11.png)

**Comment by tyronerees** [comment] 2023-05-22 12:38
I've just tested this again and it is now fixed, thanks to other changes in the codebase, so closing this issue.

**Closed by tyronerees** 2023-05-22 12:38 UTC
Labels: Bug
