### ISSUE TITLE
On result pages, where call external fit function add link to external page explaining the fit function 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [fitbenchmarking/fitbenchmarking#130] opened 2018-10-09 10:21 UTC
E.g. when calling Mantid fit function add link to external page explaining this fit function.

This test that checks these links are not broken

**Comment by tyronerees** [comment] 2019-10-03 15:05
Closing as duplicate of #196 (which has more information in the issue)

**Closed by tyronerees** 2019-10-03 15:05 UTC
Labels: Enhancement
