### ISSUE TITLE
Plotting a problem with ',' or ' ' in the name fails

### ISSUE THREAD

**Issue by AndrewLister-STFC** [fitbenchmarking/fitbenchmarking#397] opened 2020-01-16 14:40 UTC
**Description of the error**
If a problem name has a space or comma in, it will produce plots that have unconventional filenames, and worse, these are not linked properly.

To recreate this, you can run a dataset with the ENGINX236516_vanadium_bank1_10brk.txt file from the Neutron dataset.

**Describe the expected result**
Problem names should be sanitized before being used as filenames

**Describe the actual result**
Filenames can look like this: 'Fit_for_ENGINX 236516 vanadium, bank 1, 10 brk_1.png'

**Suggested fix**
FttingProblems should have name as a property which also sets an attribute such as 'sanitized_name' which can then be used for the file paths (This could alternatively be done in the FittingResult)

**Comment by tyronerees** [comment] 2020-01-16 15:41
Is this is a duplicate of #308?  The data file mentioned there no longer exists (although it didn't seem to have any illegal characters in the name).

I propose we close that issue, and work from this one -- what do you think @wathen?

**Closed** 2020-01-21 15:54 UTC
Labels: Bug
